import os

SLACK_SIGNING_SECRET=os.getenv("SLACK_SIGNING_SECRET", None)
B_SLACK_SIGNING_SECRET=SLACK_SIGNING_SECRET.encode('utf-8')
SLACK_BOT_TOKEN=os.getenv('SLACK_BOT_TOKEN', None)
SLACK_VERIFICATION_TOKEN=os.getenv('SLACK_VERIFICATION_TOKEN', None)
REDIS_HOST=os.getenv('REDIS_HOST', 'redis')
REDIS_PORT=os.getenv('REDIS_PORT','6379')
PASSWD_TTL = os.getenv('PASSWD_TTL', 2 * 60 * 60)
ENCRYPT_KEY = os.getenv('ENCRYPT_KEY', None)
